routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



Route::get('/', function () {
    return "Welcome";
});


Route::group(['middleware' => 'fw-only-whitelisted'], function () 
{
    // Authentication Routes...
    Route::get('admin/login', [
        'as' => 'admin.login',
        'uses' => 'Admin\LoginController@showLoginForm'
    ]);
    Route::post('admin/login', [
        'as' => 'admin.login.post',
        'uses' => 'Admin\LoginController@login'
    ]);
    Route::post('admin/logout', [
        'as' => 'admin.logout',
        'uses' => 'Admin\LoginController@logout'
    ]);

    Route::group(['middleware' => 'retail-only'], function ()
    {
        // Dashboard
        Route::get('/admin/dashboard', 'HomeController@index')->name('admin.dashboard');

        // JMBG routes
        Route::get('/admin/jmbgs', 'Admin\JmbgController@index')->name('admin.jmbgs');
        Route::post('/admin/jmbgs/import', 'Admin\JmbgController@import')->name('admin.jmbgs.import');

        // Applications routes
        Route::get('/admin/applications/list', 'Admin\ApplicationController@index')->name('admin.applications.list');
        Route::post('/admin/applications/export', 'Admin\ApplicationController@export')->name('admin.applications.export');
        Route::get('/admin/applications/form', 'Admin\ApplicationController@form')->name('admin.applications.form');
    });
    Route::group(['middleware' => 'marketing-only'], function ()
    {
        // Applications routes
        Route::get('/admin/marketing/list', 'Admin\MarketingController@index')->name('admin.marketing.list');
        Route::post('/admin/marketing/export', 'Admin\MarketingController@export')->name('admin.marketing.export');
        Route::get('/admin/marketing/form', 'Admin\MarketingController@form')->name('admin.marketing.form');
    });
});

// API routes
Route::post('api/check', 'ApiController@check')->middleware('cors');
Route::post('api/apply', 'ApiController@apply')->middleware('cors');
Route::post('api/marketing', 'ApiController@marketing')->middleware('cors');

app/Marketing.php
<?php

namespace App;

use App\Traits\SortableTrait;
use Illuminate\Database\Eloquent\Model;

class Marketing extends Model
{
    use SortableTrait;

    protected $table = 'marketing';

    protected $fillable = [
        'name', 'email', 'age', 'phone', 'client', 'disclaimer', 'ip_address'
    ];

    public static $_AGES = [
        1 => 'Manje od 25',
        2 =>  '25 - 40',
        3 =>  '40 - 60',
        4 =>  'Preko 60'
    ];

    public static function filterFromRequest($request)
    {
        $data = static::sortable();

        if(isset($request))
        {
            if(isset($request['date_from']))
            {
                $data = $data->whereDate('created_at', '>=', $request['date_from']);
            }
            if(isset($request['date_to']))
            {
                $data = $data->whereDate('created_at', '<=', $request['date_to']);
            }
        }

        return $data;
    }

    public static function total()
    {
        return static::all()->count();
    }

    public static function createFromRequest($request)
    {
        $created = self::create([
            'name' => $request->input('name'),
            'email' => $request->input('email'),
            'phone' => $request->input('phone'),
            'age' => $request->input('age'),
            'client' => $request->input('client'),
            'disclaimer' => $request->input('disclaimer'),
            'ip_address' => $request->has('ip') ? $request->input('ip') : $request->ip()
        ]);

        return !!$created;
    }

    public function getAgeTitleAttribute()
    {
        return static::$_AGES[$this->age];
    }

}

app/Http/Controllers/Admin/MarketingController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Marketing;
use Excel;
use App\Application;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;

class MarketingController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(Request $request)
    {
        $input = $request->input();
        $data = Marketing::filterFromRequest($input)->paginate(15);

        $total = Marketing::total();

        return view('admin.marketing.list', compact('data', 'input', 'total'));
    }

    public function export(Request $request)
    {
	    $input = $request->input();
        $marketing = Marketing::filterFromRequest($input)->get()->toArray();

        if(count($marketing) == 0)
        {
            return redirect()->back();
        }

        $data = [];
        foreach ($marketing as $key => $value) {
            $data[] = [
                'Ime i Prezime' => $value['name'],
                'E-Mail' => $value['email'],
                'Telefon' => $value['phone'],
                'Starosna dob' => Marketing::$_AGES[$value['age']],
                'Klijent banke' => $value['client'] ? 'DA' : 'NE',
                'Disclaimer' => $value['disclaimer'] ? 'DA' : 'NE',
                'IP' => $value['ip_address']
            ];
        }

        $excel = Excel::create('export_'.date('Ymd_Hi'), function($excel) use ($data)
        {
            $excel->sheet('Sheet 1', function($sheet) use ($data) {
                $sheet->fromArray($data);
            });
        });

        // work on the export
        return $excel->download('xls');
    }

    public function form()
    {
        return view('admin.marketing.form');
    }
}

resources/views/admin/marketing/_export.blade.php
<form name="applications-export" method="post" action="{{route('admin.marketing.export')}}">
    @component('admin.widgets.panel')
        @slot('panelTitle')
            Export
        @endslot
        @slot('panelBody')
            {{csrf_field()}}
            <div class="form-group">
                <label>Datum od: </label>
                <input type="text" name="date_from" class="form-control datepicker" value="{{$date_from}}">
            </div>
            <div class="form-group">
                <label>Datum do: </label>
                <input type="text" name="date_to" class="form-control datepicker" value="{{$date_to}}">
            </div>
        @endslot
        @slot('panelFooter')
            <input type="submit" class="btn btn-primary btn-sm" value="Exportuj">
        @endslot
    @endcomponent
</form>

resources/views/admin/marketing/_filter.blade.php
<form name="marketing-filters" id="marketing-filters" class="form-inline" method="get">
    <div class="form-group">
        <label><strong>OD:</strong>&nbsp;</label>
        <input type="text" name="date_from" class="form-control input-sm datepicker" value="{{$date_from}}">
    </div>
    &emsp;
    <div class="form-group">
        <label><strong>DO:</strong>&nbsp;</label>
        <input type="text" name="date_to" class="form-control input-sm datepicker" value="{{$date_to}}">
    </div>
    &emsp;
    <div class="form-group">
        <input type="submit" class="btn btn-primary btn-sm" value="Filtriraj">
        <a href="{{route('admin.applications.list')}}" class="btn btn-danger btn-sm">Poništi</a>
    </div>
</form>

resources/views/admin/marketing/_table.blade.php
<?php use App\Traits\SortableTrait; ?>
@if(count($data))
    <table class="table table-striped">
        <thead>
        <tr>
            <th>{!! SortableTrait::linkZoSortingAction('id', 'ID') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('name', 'Ime i Prezime') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('email', 'Email') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('phone', 'Telefon') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('client', 'Klijent') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('age', 'Starosna dob') !!}</th>
            <th>{!! SortableTrait::linkZoSortingAction('ip_address', 'IP adresa') !!}</th>
        </tr>
        </thead>
        <tbody>
        @foreach($data as $row)
            <tr>
                <td>{{$row->id}}</td>
                <td>{{$row->name}}</td>
                <td>{{$row->email}}</td>
                <td>{{$row->phone}}</td>
                <td>{{$row->client ? 'DA' : 'NE'}}</td>
                <td>{{$row->age_title}}</td>
                <td>{{$row->ip_address}}</td>
            </tr>
        @endforeach
        </tbody>
        @if($data->count() > 15)
            <tfoot>
            <tr>
                <td colspan="3" class="text-right" style="margin: 0;">
                    {{$data->appends($input)->links()}}
                </td>
            </tr>
            </tfoot>
        @endif
    </table>
@else
    @include('admin.widgets.alert', ['class'=>'alert-info', 'message'=>'Nema podataka.'])
@endif

resources/views/admin/marketing/form.blade.php
@extends('admin.layouts.dashboard')

@section('page_heading', 'Prijava Test')

@section('section')
    <div class="col-sm-6" id="marketing-form-container">
        <form name="marketing-form" id="marketing-form">
            @component('admin.widgets.panel')
                @slot('panelBody')
                    <div class="form-group">
                        <label>Ime i prezime: </label>
                        <input type="text" name="name" class="form-control">
                        <p id="name-errors" class="text-danger"></p>
                    </div>
                    <div class="form-group">
                        <label>E-Mail: </label>
                        <input type="text" name="email" class="form-control">
                        <p id="email-errors" class="text-danger"></p>
                    </div>
                    <div class="form-group">
                        <label>Telefon: </label>
                        <input type="text" name="phone" class="form-control">
                        <p id="phone-errors" class="text-danger"></p>
                    </div>
                    <div class="form-group">
                        <label>Starosna dob: </label>

                        <div class="radio">
                            <label>
                                <input type="radio" name="age" id="age1" value="1"> Manje od 25
                            </label>
                            &emsp;
                            <label>
                                <input type="radio" name="age" id="age2" value="2"> 25 - 40
                            </label>
                            &emsp;
                            <label>
                                <input type="radio" name="age" id="age3" value="3"> 40 - 60
                            </label>
                            &emsp;
                            <label>
                                <input type="radio" name="age" id="age4" value="4"> Preko 60
                            </label>
                        </div>

                        <p id="age-errors" class="text-danger"></p>
                    </div>
                    <div class="form-group">
                        <label>Da li ste klijent banke?</label>

                        <div class="radio">
                            <label>
                                <input type="radio" name="client" id="age1" value="1"> Da
                            </label>
                            &emsp;
                            <label>
                                <input type="radio" name="client" id="age2" value="0"> Ne
                            </label>
                        </div>

                        <p id="client-errors" class="text-danger"></p>
                    </div>
                    <div class="form-group">
                        <label>
                           <input type="checkbox" name="disclaimer" id="disclaimer"> Unosom gore navedenih podataka, potvrđujem da sam saglasan da Sparkasse Bank d.d. BiH čuva, obrađuje i koristi moje lične podatke iz ovog ispunjenog obrasca: ime i prezime/broj telefona/e-mail, a u svrhu učešća u nagradnoj igri koju organizira i provodi Sparkasse Bank dd BiH, kao i promotivnih i prodajnih aktivnosti, direktnog marketinga, analize i istraživanja. Ova saglasnost ne može se koristiti u druge svrhe od navedenih, a dajem je na neograničen vremenski period, do vlastitog opoziva iste.
                        </label>
                        <p id="disclaimer-errors" class="text-danger"></p>
                    </div>
                @endslot
                @slot('panelFooter')
                    <input type="submit" id="form-submit" class="btn btn-primary btn-sm" value="Dodaj" style="display:none">
                @endslot
            @endcomponent
        </form>
    </div>
    <div class="col-sm-6" id="success-message-container" style="display: none">
        <div class="alert alert-success" role="alert">
            Hvala Vam za učešće u nagradnoj igri.
        </div>
    </div>

    <script src="{{ asset("js/form-marketing.js") }}"></script>
@endsection

resources/views/admin/marketing/list.blade.php
@extends('admin.layouts.dashboard')

@section('page_heading','Prijave')

@section('section')
    <div class="col-sm-12 col-md-10 col-lg-8">
        @component('admin.widgets.panel')
            @slot('panelBody')
                @include('admin.marketing._filter', [
                    'date_from' => isset($input['date_from']) ? $input['date_from'] : '',
                    'date_to' => isset($input['date_to']) ? $input['date_to'] : ''
                ])
            @endslot
            @slot('panelTable')
                @include('admin.marketing._table', ['data'=>isset($data) ? $data : []])
                <div class="text-center">
                    {{$data->links()}}
                </div>
            @endslot
            @slot('panelFooter')
                Ukupno prijava: <strong>{{$total}}</strong>
            @endslot
        @endcomponent
    </div><!-- /.col-sm-6 -->
    <div class="col-sm-12 col-md-2 col-lg-4">
        @include('admin.marketing._export', [
            'date_from' => isset($input['date_from']) ? $input['date_from'] : '',
            'date_to' => isset($input['date_to']) ? $input['date_to'] : ''
        ])
    </div><!-- /.col-sm-4 -->
@endsection